version: '3'
services:
  php:
    image: php:fpm
    volumes:
      - ./code:/code
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./code:/code
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./server_logs:/var/log/nginx
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=testdb
      - DB_USERNAME=root
      - DB_PASSWORD=root
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
    volumes:
      - ./db_data:/var/lib/mysql